baseURL = 'http://domacidzem.cz/'
title = 'DOMÁCÍ DŽEM alias DomaDžem'
theme = 'ananke.v2'
resourceDir = "../resources"
defaultContentLanguage = "czech"


[params]
author = "DOMÁCÍ DŽEM"
recent_posts_number = 1
mainSections = ["post"]
background_color_class = "bg-mid-gray"
cover_dimming_class = "bg-black-30"
dimming_class = "bg-black-30"
[params.ananke.social.follow]
networks = ["facebook", "youtube", "instagram"]

[params.ananke.social.facebook]
profilelink = "https://www.facebook.com/domadzem"

[params.ananke.social.youtube]
profilelink = "https://www.youtube.com/@domacidzem"

[params.ananke.social.instagram]
profilelink = "https://www.instagram.com/domadzem"

[languages]
[languages.czech]
languageCode = 'cs-cz'
weight = 1
contentDir = "content/cz"
[languages.english]
languageCode = 'en-US'
weight = 2
contentDir = "content/en"