baseURL = 'http://domacidzem.cz/'
title = 'DOMÁCÍ DŽEM'
theme = 'ananke'
resourceDir = "../resources"
defaultContentLanguage = "czech"

[[params.ananke_socials]]
name = "facebook"
url = "https://www.facebook.com/domadzem"

[params]
author = "DOMÁCÍ DŽEM"
recent_posts_number = 1
mainSections = ["post"]
background_color_class = "bg-mid-gray"
cover_dimming_class = "bg-black-30"
dimming_class = "bg-black-30"

[languages]
[languages.czech]
languageCode = 'cs-cz'
weight = 1
contentDir = "content/cz"
[languages.english]
languageCode = 'en-US'
weight = 2
contentDir = "content/en"